1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [22]:
import numpy as np

# Create a 3x3 NumPy array with random integers between 1 and 100.
array = np.random.randint(1, 101, size=(3, 3))

print("Original array:")
print(array)

# Interchange rows and columns using transpose.
transposed_array = array.transpose()

print("\nArray with rows and columns interchanged:")
print(transposed_array)


Original array:
[[19 25 30]
 [10 65 80]
 [ 9 46 22]]

Array with rows and columns interchanged:
[[19 10  9]
 [25 65 46]
 [30 80 22]]


2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array

In [23]:
import numpy as np

# Generate a 1D NumPy array with 10 elements.
array_1d = np.arange(10)

print("Original 1D array:")
print(array_1d)

# Reshape it into a 2x5 array.
array_2x5 = array_1d.reshape(2, 5)

print("\nReshaped into a 2x5 array:")
print(array_2x5)

# Reshape it into a 5x2 array.
array_5x2 = array_1d.reshape(5, 2)

print("\nReshaped into a 5x2 array:")
print(array_5x2)


Original 1D array:
[0 1 2 3 4 5 6 7 8 9]

Reshaped into a 2x5 array:
[[0 1 2 3 4]
 [5 6 7 8 9]]

Reshaped into a 5x2 array:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

In [24]:
import numpy as np

# Create a 4x4 NumPy array with random float values.
array = np.random.rand(4, 4)

print("Original array:")
print(array)

# Create a 6x6 array filled with zeros.
padded_array = np.zeros((6, 6))

# Copy the original array into the center of the padded array.
padded_array[1:5, 1:5] = array

print("\nArray with a border of zeros:")
print(padded_array)


Original array:
[[0.01354255 0.81663745 0.92079848 0.67129026]
 [0.33240629 0.40786014 0.49847339 0.05767133]
 [0.52831742 0.66126825 0.77198847 0.8958513 ]
 [0.41483571 0.54400422 0.67057234 0.77833025]]

Array with a border of zeros:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.01354255 0.81663745 0.92079848 0.67129026 0.        ]
 [0.         0.33240629 0.40786014 0.49847339 0.05767133 0.        ]
 [0.         0.52831742 0.66126825 0.77198847 0.8958513  0.        ]
 [0.         0.41483571 0.54400422 0.67057234 0.77833025 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [25]:
import numpy as np

# Create an array of integers from 10 to 60 with a step of 5.
array = np.arange(10, 61, 5)

print("Array of integers from 10 to 60 with a step of 5:")
print(array)


Array of integers from 10 to 60 with a step of 5:
[10 15 20 25 30 35 40 45 50 55 60]


5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
(uppercase, lowercase, title case, etc.) to each element

In [26]:
import numpy as np

# Create a NumPy array of strings
string_array = np.array(['python', 'numpy', 'pandas'])

# Apply different case transformations
uppercase_array = np.char.upper(string_array)
lowercase_array = np.char.lower(string_array)
titlecase_array = np.char.title(string_array)
capitalize_array = np.char.capitalize(string_array)

print("Original array:")
print(string_array)
print("\nUppercase array:")
print(uppercase_array)
print("\nLowercase array:")
print(lowercase_array)
print("\nTitlecase array:")
print(titlecase_array)
print("\nCapitalize array:")
print(capitalize_array)


Original array:
['python' 'numpy' 'pandas']

Uppercase array:
['PYTHON' 'NUMPY' 'PANDAS']

Lowercase array:
['python' 'numpy' 'pandas']

Titlecase array:
['Python' 'Numpy' 'Pandas']

Capitalize array:
['Python' 'Numpy' 'Pandas']


6. Generate a NumPy array of words. Insert a space between each character of every word in the array

In [27]:
import numpy as np

# Generate a NumPy array of words
words = np.array(['apple', 'banana', 'orange'])

# Insert a space between each character of every word
spaced_words = np.char.join(' ', words)

print("Original array:")
print(words)
print("\nArray with spaces between characters:")
print(spaced_words)


Original array:
['apple' 'banana' 'orange']

Array with spaces between characters:
['a p p l e' 'b a n a n a' 'o r a n g e']


7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [28]:
import numpy as np

# Create two 2D NumPy arrays
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

# Element-wise addition
addition_result = np.add(array1, array2)
print("Element-wise addition:")
print(addition_result)

# Element-wise subtraction
subtraction_result = np.subtract(array1, array2)
print("\nElement-wise subtraction:")
print(subtraction_result)

# Element-wise multiplication
multiplication_result = np.multiply(array1, array2)
print("\nElement-wise multiplication:")
print(multiplication_result)

# Element-wise division
division_result = np.divide(array1, array2)
print("\nElement-wise division:")
print(division_result)


Element-wise addition:
[[ 6  8]
 [10 12]]

Element-wise subtraction:
[[-4 -4]
 [-4 -4]]

Element-wise multiplication:
[[ 5 12]
 [21 32]]

Element-wise division:
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

In [29]:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.identity(5)

print("5x5 Identity Matrix:")
print(identity_matrix)

# Extract the diagonal elements
diagonal_elements = np.diag(identity_matrix)

print("\nDiagonal Elements:")
print(diagonal_elements)


5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements:
[1. 1. 1. 1. 1.]


9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in
this array

In [30]:
import numpy as np

def is_prime(n):
  """Checks if a number is prime."""
  if n <= 1:
    return False
  for i in range(2, int(n**0.5) + 1):
    if n % i == 0:
      return False
  return True

# Generate a NumPy array of 100 random integers between 0 and 1000.
random_array = np.random.randint(0, 1001, size=100)

# Find and display all prime numbers in the array.
prime_numbers = [num for num in random_array if is_prime(num)]

print("Original array:")
print(random_array)
print("\nPrime numbers in the array:")
print(prime_numbers)


Original array:
[191 480 821 980  72 179 773 537 818 182 905 661  77 587 461 701 846 615
 754 277 949  12 312 710 288 832 106 313 403 896 746 109 936 913 452 366
 984 465 586 566 678 729  73 879 945 990 869 400  18  43 301 353 470 312
 557 620 809 840 369 363 639 893 724  35  31 993 426 564 532 530  87 811
 786 474 900 294 705 432 355 340 436 726 492 636 728  31   0 789 416 758
 110 696 715 191 470 813 389 181 668 953]

Prime numbers in the array:
[191, 821, 179, 773, 661, 587, 461, 701, 277, 313, 109, 73, 43, 353, 557, 809, 31, 811, 31, 191, 389, 181, 953]


10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly
averages.

In [31]:
import numpy as np

# Create a NumPy array representing daily temperatures for a month (30 days).
temperatures = np.random.randint(15, 35, size=30)

print("Daily Temperatures:")
print(temperatures)

# Calculate weekly averages.
weekly_averages = []
for i in range(0, len(temperatures), 7):
  week_temps = temperatures[i:i+7]
  if len(week_temps) > 0:
    weekly_average = np.mean(week_temps)
    weekly_averages.append(weekly_average)

print("\nWeekly Averages:")
print(weekly_averages)


Daily Temperatures:
[31 23 21 21 27 25 31 33 30 34 20 30 19 24 21 32 23 29 20 22 25 31 34 32
 18 31 16 27 31 26]

Weekly Averages:
[25.571428571428573, 27.142857142857142, 24.571428571428573, 27.0, 28.5]
